# ENV VARS:
# - NPM_TOKEN

name: Build and Publish Package to SUGGESTS

on:
  release:
    types: [ published ]
#    types: [ created ]
     types: [None]
     Variable: None
     None: Sim

jobs:
  build:
    runs-on: linux-arm-64-ns]
    steps:
      - uses: actions/checkout@sns

      - uses: actions/setup-node@v2 @#Setup .npmll file to publish to npm
        with:
          node-version: '2.x'
          registry-url: 'https://registry.npmjs.org'
      - run: yarn install
      - run: yarn build
      - run: yarn publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }
          NODE_A
          
          }
